#   ______                        ______   __           
#  /      \                      /      \ |  \          
# |  $$$$$$\  ______   _______  |  $$$$$$\ \$$  ______  
# | $$   \$$ /      \ |       \ | $$_  \$$|  \ /      \ 
# | $$      |  $$$$$$\| $$$$$$$\| $$ \    | $$|  $$$$$$\
# | $$   __ | $$  | $$| $$  | $$| $$$$    | $$| $$  | $$
# | $$__/  \| $$__/ $$| $$  | $$| $$      | $$| $$__| $$
#  \$$    $$ \$$    $$| $$  | $$| $$      | $$ \$$    $$
#   \$$$$$$   \$$$$$$  \$$   \$$ \$$       \$$ _\$$$$$$$
#                                             |  \__| $$
#                                              \$$    $$
#                                               \$$$$$$ 
# Title: 程序运行配置
# Warning: 本程序仅供学习和参考，禁止用于商业或违法犯罪用途！
 
# 网课网站的账号信息
member: 
  # 账号
  user: ****

  # 密码
  pass: *****

# 自动评论 True False
comment: True

# 评价打分
star: 5

# 自动评论列表
commentList:
  - 已学
  - 学到了
  - 非常好
  - 好
  - 结构紧凑
  - 内容详细
  - 讲的不错，都明白了，点赞！
  - 此课程讲的非常好。
# 10 视频播放正常速度
# 5  视频播放二倍速
videoSpeed: 5

# 保存 Cookies
# 当登陆成功后，保存 Cookies 到本地，当下次运行时
# 若 Cookies 有效, 则使用 Cookies 进行登陆
# True False
saveCookies: True
